# Linting of Arduino repository

name: "Linting Status"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Arduino Linter
      - name: arduino/arduino-lint-action
        uses: arduino/arduino-lint-action@v1.0.1
        with:
          # Path containing Arduino projects.
          path: ./megaavr
          # How strict the checks are.
          compliance: permissive
          # The type of project to check.
          project-type: platform
          # Search path recursively for projects to check.
          recursive: false
          # Save a JSON formatted report on the checks to this file.
          report-file: false
          # Show more information on the checks being run.
          verbose: false

